### ISSUE TITLE
Info HUD hotkey doesn't ConsumePress

### ISSUE THREAD

**Issue by vivianlonging** [DemoJameson/CelesteSpeedrunTool#10]
Kinda enough said tbh, it just needs a ConsumePress added to the function so that it doesn't turn on and off every frame.

**Comment by vivianlonging** [comment]
my bad lol wrong helper

**Comment by DemoJameson** [comment]
@Viv-0 nvm, this issue should be fixed.
https://github.com/EverestAPI/CelesteTAS-EverestInterop/commit/dbe0b70435d7572c803b9f6473092cbc357baebd
