### ISSUE TITLE
希望reload次数能计入死亡次数

### ISSUE THREAD

**Issue by liushengqi000** [DemoJameson/CelesteSpeedrunTool#21]
死亡后reload似乎并不会增加死亡次数，我想知道自己确切死亡次数

**Comment by DemoJameson** [comment]
关掉保存时间和死亡数就行

**Comment by liushengqi000** [comment]
> 关掉保存时间和死亡数就行

我刚测试关闭状态，似乎时间会累积，但死亡次数没有增加

**Comment by liushengqi000** [comment]
应该说，Death Tracker在左上角的本次死亡次数没有增加

**Comment by DemoJameson** [comment]
death tracker 啊，那等我有空看看

**Comment by liushengqi000** [comment]
> death tracker 啊，那等我有空看看

刚去检查了春游总死亡次数，确实增加了

**Comment by liushengqi000** [comment]
> death tracker 啊，那等我有空看看

感谢你的工作:P
