### ISSUE TITLE
Save state Interop

### ISSUE THREAD

**Issue by mayromr** [DemoJameson/CelesteSpeedrunTool#26]
Hey, I was wondering if it could be possible to expose an API for saving a state and then restoring to a given state. I have an idea for a mod that could use this functionality. 
I looked at [SpeedrunToolInterop.cs](https://github.com/DemoJameson/CelesteSpeedrunTool/blob/master/SpeedrunTool/Source/SpeedrunToolInterop.cs) and I only found support for adding other modded content into the save state.

Something like this would be awesome:
```c#
public static State SaveState() {...}
public static void LoadState(State state) {...}
```

**Comment by DemoJameson** [comment]
Current implementation cannot store state in an object, so it can only do something like this
```cs
public static bool TrySaveState() {...}
public static bool TryLoadState() {...}
```

**Comment by mayromr** [comment]
Aight looks good, Ill try playing around with the code at the `SaveLoad` dir.
