### ISSUE TITLE
我应该如何让自己的mod与“保存状态”兼容?

### ISSUE THREAD

**Issue by wuke32767** [DemoJameson/CelesteSpeedrunTool#33]
目前已知是一些静态变量没有保存。

**Comment by DemoJameson** [comment]
如果只是静态变量可以用 SpeedrunTool 提供的跨 Mod API 来处理，具体请看

https://github.com/DemoJameson/Celeste.SpeedrunTool/blob/master/SpeedrunTool/Source/SpeedrunToolInterop.cs#L50-L66

https://github.com/EverestAPI/Resources/wiki/Cross-Mod-Functionality#modinterop
