### ISSUE TITLE
在磁带面save会导致所有关卡音乐消失

### ISSUE THREAD

**Issue by WEGFan** [DemoJameson/CelesteSpeedrunTool#7]
进入到磁带面后按save后，磁带面的音乐会消失，退出房间重进后能重新播放，关卡内音乐消失，只能通过重启游戏解决
Everest v1.1900.0
SpeedrunTool v2.1.19

**Comment by DemoJameson** [comment]
v2.0 版本不再维护了，v3.0 开发中没发现这个问题
